### ISSUE TITLE
Incompatible with the Easy Magic mod

### ISSUE THREAD

**Issue by Papaturts** [Shadows-of-Fire/Apothic-Enchanting#13]
Seems there is an incompatibility with the Easy magic mod
When said mod is installed, the eterna, quanta and arcana is not showing up inside the enchanting table.
This is on 1.21.1 neoforge

**Comment by meeprdib** [comment]
They are incompatible by nature because they are both overriding the vanilla enchanting table. Choose one enchanting mod over the other.

**Comment by Papaturts** [comment]
I did
I choose You!!!
