### ISSUE TITLE
Apothic Enchanting's system breaks with datapacks

### ISSUE THREAD

**Issue by TomatoSoupter** [Shadows-of-Fire/Apothic-Enchanting#14]
Using a specific type of data file to remove enchantments breaks the enchanting system, making everything list as "Limited Enchantibility" and effectively disabling the ability to enchant items.

Steps to reproduce:
1: Create a file with the filepath data/<modid>/enchantments/<enchantment_id>.json
2: Paste `{"neoforge:conditions":[{"type":"neoforge:false"}]}` into the file and save
3: Launch world with datapack and attempt to enchant something
4: All options say "Limited Enchantibility" regardless of enchanting table configuration

Apothic Enchanting Version: 1.21.1-1.2.3 Neoforge

**Comment by Shadows-of-Fire** [comment]
Simply creating a datapack with a false override for an enchantment json is likely to break any tags dependent on that enchantment being loaded. Check your game log, if you see any `Couldn't load tag ...` messages, you have broken those tags by removing the entry.  You **must** fix those tags for the game to operate properly.

This is not functionality specific to apothic enchanting, and is the case when doing this in vanilla.
