### ISSUE TITLE
Feature Placement crash

### ISSUE THREAD

**Issue by djnifos** [Shadows-of-Fire/Apothic-Enchanting#3]
When playing with this mod on a server, feature placement in the nether the mod seems to call client code in a server instance. 

Neo 21.0.163
Apothic Ench 1.21-1.1.1
Placebo 1.21-9.3.5
(ATM 10)

Latest Log:
https://mclo.gs/NmkHkTP

**Comment by Shadows-of-Fire** [comment]
f320f911cae8e255a845b64ab8a97de757a534de
